/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvaluateIndexRouteImport } from './routes/evaluate/index'
import { Route as WriteIdRouteImport } from './routes/write/$id'
import { Route as EvaluateIdRouteImport } from './routes/evaluate/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluateIndexRoute = EvaluateIndexRouteImport.update({
  id: '/evaluate/',
  path: '/evaluate/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIdRoute = WriteIdRouteImport.update({
  id: '/write/$id',
  path: '/write/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluateIdRoute = EvaluateIdRouteImport.update({
  id: '/evaluate/$id',
  path: '/evaluate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/editor': typeof EditorRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/signup': typeof SignupRoute
  '/evaluate/$id': typeof EvaluateIdRoute
  '/write/$id': typeof WriteIdRoute
  '/evaluate/': typeof EvaluateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/editor': typeof EditorRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/signup': typeof SignupRoute
  '/evaluate/$id': typeof EvaluateIdRoute
  '/write/$id': typeof WriteIdRoute
  '/evaluate': typeof EvaluateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/editor': typeof EditorRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/signup': typeof SignupRoute
  '/evaluate/$id': typeof EvaluateIdRoute
  '/write/$id': typeof WriteIdRoute
  '/evaluate/': typeof EvaluateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/editor'
    | '/library'
    | '/login'
    | '/redirect'
    | '/signup'
    | '/evaluate/$id'
    | '/write/$id'
    | '/evaluate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/editor'
    | '/library'
    | '/login'
    | '/redirect'
    | '/signup'
    | '/evaluate/$id'
    | '/write/$id'
    | '/evaluate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/editor'
    | '/library'
    | '/login'
    | '/redirect'
    | '/signup'
    | '/evaluate/$id'
    | '/write/$id'
    | '/evaluate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EditorRoute: typeof EditorRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  SignupRoute: typeof SignupRoute
  EvaluateIdRoute: typeof EvaluateIdRoute
  WriteIdRoute: typeof WriteIdRoute
  EvaluateIndexRoute: typeof EvaluateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluate/': {
      id: '/evaluate/'
      path: '/evaluate'
      fullPath: '/evaluate/'
      preLoaderRoute: typeof EvaluateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/$id': {
      id: '/write/$id'
      path: '/write/$id'
      fullPath: '/write/$id'
      preLoaderRoute: typeof WriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluate/$id': {
      id: '/evaluate/$id'
      path: '/evaluate/$id'
      fullPath: '/evaluate/$id'
      preLoaderRoute: typeof EvaluateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EditorRoute: EditorRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  SignupRoute: SignupRoute,
  EvaluateIdRoute: EvaluateIdRoute,
  WriteIdRoute: WriteIdRoute,
  EvaluateIndexRoute: EvaluateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
